### ISSUE TITLE
[INVALID] Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [alonbl/mp3unicode#1]
Dear Alon,
Could you be so kind to generate ```.exe``` for the rest of us who use Windows, if possible?

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by alonbl** [comment]
Hi,
I am unsure this is possible, maybe I will have time during the weekend to
check it out.
Alon

**Comment by sergeevabc** [comment]
Six months passed. Err… Hello?

**Comment by alonbl** [comment]
Last time I checked it was difficult to cross-compile taglib for windows,
so you should probably look into other solutions or use Linux.
